### PR TITLE
Quickpi sensor start

### PR DESCRIPTION
**Pull request by NicolasWent**
With this code:

When user do manipulation in his experiment tab and then try to run his program on these modifications, his modifications inside of the "experiment TAB" will be saved at run (in master it reset the tab on start of program).

And also, at the end of the program, the "experiment TAB" will be reset to what was at the start of his program. So he can run his program again with exactly the same parameters.

### CODE REVIEW

**Review by mblockelet — CHANGES_REQUESTED** [review]
Hello,

In short, it doesn't work, my very first test didn't pass (it was on 1-melodie, just clicking the buzzer on).

The main issue is that restoreSensors is only called in one specific case : the program ends. In many cases, we won't get to the program end before a reset, first because in quick-pi neverending programs are common, but also because users will often stop their program before the end when they're testing something.

You should also take care because the sensors reset also initializes their state in some cases, so you might want to check that you're not interfering with that.

You might want to save the state of a sensor when it's modified by the user, as it's the best way to ensure you save at the right time.

**Comment by NicolasWent** [comment]
Hello, thank you for your comments, I have done a new version to answer your comments

> Hello,
> 
> In short, it doesn't work, my very first test didn't pass (it was on 1-melodie, just clicking the buzzer on).

In 1-melodie, there is only the buzzer and the buzzer is not considered as a sensor, I can add a particular case for it or change it to be a sensor. Because I only save the state of elements which are sensors, maybe we need a list of components which are not sensors but must be saved?

> The main issue is that restoreSensors is only called in one specific case : the program ends. In many cases, we won't get to the program end before a reset, first because in quick-pi neverending programs are common, but also because users will often stop their program before the end when they're testing something.

I have changed the restoreSensor method to be called when the user stop and when the program end with the pattern observer which "catch" the stop event.

> You should also take care because the sensors reset also initializes their state in some cases, so you might want to check that you're not interfering with that.

Now the method resetSensors is called once at the loading of the page to be sure that the sensors are getting loaded at least once.

> You might want to save the state of a sensor when it's modified by the user, as it's the best way to ensure you save at the right time.

I have found the method "drawSensor" which is called at each modification, but I don't think that it is the right approach, since this function is a little "random" and the function is also called during the execution, so I must find a way to know when we started to stop saving. But if I know when the program started so I can just do a "save all" to save all sensors when the program has started

**Review by mblockelet — CHANGES_REQUESTED** [review]
Sorry, but as I had said on Slack, it's a very bad idea to have onLoad, onStart, onStop. For both start and stop your logic is wrong (both the logic of when to call them, and the logic of what to do then), and actually adds issues more than it solves anything.

To give two examples of why it's wrong (there are many more cases which are not covered) :
* onStop is only called when the program ends normally. It is not called on other cases (not going to test for each case but that might or might not include : when the program has an error ; when the program is stopped in the middle of execution by the user ; when the program is an infinite loop).
* Restoring sensors when onStop is called means that the user will never see the final state, as it gets erased by restoreSensors as soon as the program ends, and not when the reset happens.

That's why I suggested to look into restoring the sensors state when context.reset is called, and saving them when a user modification is done.

Also, your code doesn't seem to handle the case where there are different sensors for different difficulties.

**Comment by NicolasWent** [comment]
Hello,

Let me first clarify the specs of this update, to make sure that we are thinking about the same thing:
The original bug, was that the user tried to modify some of the sensors and then, when he start the program to try it on for example a specific distance, all of the sensors are reset to default, so his program start with the default distance instead of the one he wanted. So, one of the aim of this update is to not reset the sensors when the user lunch the program so he can test it with the values he wanted.
You said on slack that it would be also good to restore the sensors to what it was when the user start his program at the end of it, so he can try to restart it with exactly the same parameters two times.

> Sorry, but as I had said on Slack, it's a very bad idea to have onLoad, onStart, onStop. For both start and stop your logic is wrong (both the logic of when to call them, and the logic of what to do then), and actually adds issues more than it solves anything.

I don't understand why it is wrong. At the begining of the program, we must anyway find a way to know when the user click on the button "start" to run his program, the function "context.reset" is indeed called, but this function is also called when the exercice is loaded, when the user click on the button "backToFirst" (and some more cases), thats why I decided to create my own event which can be called "when the user click on the button start", so at this moment we save the sensors.

If the problem is this function we can remove it if we find another way of knowing when the user click on the start button.

>     * onStop is only called when the program ends normally. It is not called on other cases (not going to test for each case but that might or might not include : when the program has an error ; when the program is stopped in the middle of execution by the user ; when the program is an infinite loop).

For onStop, I agree that there was some problems, there was actually the function "context.onExecutionEnd", which is called when there is an error and when the program end (basically, in blocklyQuickpi_lib.js, when it end we "throw", and the this throw is catched and call the function context.onExecutionEnd), but this function was not called when the user click on the button "backToFirst" to restart the program, thats why I created the event "onStop" which is fired everytime the program stops (and I also called it inside of the context.onExecutionEnd). By "stops" I mean when the execution of it is complety stopped by an error, user action, normal end. When the program is inside of an infine loop, it should not stop running unless the user click on the button "backToFirst" or pause it, but when he pause it nothing change in his sensors.

>     * Restoring sensors when onStop is called means that the user will never see the final state, as it gets erased by restoreSensors as soon as the program ends, and not when the reset happens.

I thought that it was the aim of the update, as I said in the spec reminder: The sensors are restored at the state they were when the program starts. Moreover, only "sensors" are restored which are elements that cannot be modified by the code but only by the user inside of the editor. So he will see the screen the leds and all the things that he can not modify otherwise than with the code but the elements which he can modify "by hand" will be restored to what they where when the user started the program.

> That's why I suggested to look into restoring the sensors state when context.reset is called, and saving them when a user modification is done.

The function context.reset is not called when the program end normally, only when we click on "backToFirst" button (and also in some other cases like loading...). So if we use this function, we will have to do some special cases to call it everytime the program end (error, normal ending...)

> Also, your code doesn't seem to handle the case where there are different sensors for different difficulties.

Thats why there is the "onLoad" function, this function is called everytime the difficulty of an exercice change in order to load all the sensors of this difficulty (I have tried to see when it is called with some console.log and it was called at every difficulty change). If you change difficulty, your program stop anyway, we have save the state of the sensors of the other difficulty, but since there is no stop in the program (because it is not running), then there is not issue with that, even when you click on the button "reset", after changing difficulty there is no error displayed.

I did not found any issue with this version, actually there is maybe one but I can modify it in the next push:
When we modify the sensors and click on the button "backToFirst" and the program is not running, then we should reset the sensors to default I think (currently this button does nothing when we click on it without lunching the program), I don't know what you think of it?

**Comment by mblockelet** [comment]
Replaced by #60.

**Pull request closed without merging**
